[CONTENT REVIEW] 10.4 - Atualização do Readme do projeto Jest assíncrono e mocking
betrybe/sd-0x-project-jest pull request #10
Opened 2020-11-19 13:58 UTC by isabellavjs

Closes #2296

2020-12-02 12:22 UTC, LizzardMedeiros requested changes
Oi, Isa! O @phelipe-ohlsen, @albertosca e eu chegamos a um padrão mais robusto de readme, alinhando tanto as [regras da apresentação da Betina](https://docs.google.com/presentation/d/1uyKtkDgs8f3_i4mCIkAKsNx1E0HLe42jxoT4fBq21xg/edit?ts=5fb50741) quanto a estética e facilidade de leitura.

Ainda não está 100%, sugestões são muito bem vindas! Dê uma conferida:

[Link do playbook](https://gist.github.com/LizzardMedeiros/81d758d23e6ce085c8e58c7a5394195d)

2020-12-02 12:22 UTC, LizzardMedeiros commented on README.md
> +Ao iniciar este projeto, você concorda com as diretrizes do Código de Ética e Conduta e do Manual da Pessoa Estudante da Trybe.
Oi, Isa! Se puder inserir aqui o título ` ### Termos de acordos` ficará mais dentro do nosso [novo padrão](https://gist.github.com/LizzardMedeiros/81d758d23e6ce085c8e58c7a5394195d) =)

2020-12-02 12:22 UTC, LizzardMedeiros commented on README.md
> +
Acho que fica mais estético retirar as linhas em branco entre os tópicos, o que vc acha?
@phelipe-ohlsen, concorda?

2020-12-02 12:22 UTC, LizzardMedeiros commented on README.md
> +## HABILIDADES
Definimos no novo padrão que fica mais estético e lógico colocas as habilidades abaixo do sumário =)

2020-12-02 14:40 UTC, isabellavjs reviewed
Obrigada Lizz! O tutorial que vc enviou está atualizado? Já subi com as correções seguindo o novo padrão. Falta algumas coisas que ficamos de conferir com o Roz, como a parte de testar os testes que os estudantes escrevem.

2020-12-02 14:40 UTC, isabellavjs commented on README.md
> +Ao iniciar este projeto, você concorda com as diretrizes do Código de Ética e Conduta e do Manual da Pessoa Estudante da Trybe.
Obrigada @LizzardMedeiros ! Vou adicionar aqui. Uma pergunta, esse link que vc passou pro novo padrão está atualizado? Porque esse titulo para o termos de acordo está faltando no documento e no README do Trybe wallet

2020-12-02 14:40 UTC, isabellavjs commented on README.md
> +## HABILIDADES
Concordo, corrigido!

2020-12-07 12:34 UTC, LizzardMedeiros requested changes
Oi Isa! Então, parece que algumas coisas estão fora do padrão do [playbook](https://gist.github.com/LizzardMedeiros/81d758d23e6ce085c8e58c7a5394195d), por exemplo, os títulos devem ficar em caixa-baixa no tamanho h1, certifique-se também que os tópicos estão na ordem correta =)

Obrigado

2020-12-07 16:06 UTC, roziscoding approved these changes

2020-12-08 11:28 UTC, LizzardMedeiros approved these changes

2020-12-08 11:31 UTC, merged